// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuUfsd2AgkIrU7UeHqwNt-KBHSS6jg_rI',
    appId: '1:882514435162:web:63152381d03ae5b8618c63',
    messagingSenderId: '882514435162',
    projectId: 'tododemoproject',
    authDomain: 'tododemoproject.firebaseapp.com',
    storageBucket: 'tododemoproject.appspot.com',
    measurementId: 'G-P8FG9CG0LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpi4xGp4GWCBacnhpkFoQGMXwsKMhpWjI',
    appId: '1:882514435162:android:e4c77aae04583806618c63',
    messagingSenderId: '882514435162',
    projectId: 'tododemoproject',
    storageBucket: 'tododemoproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEv2bnnEIdFt7Gl_PwfL00HYnFdDFTG_E',
    appId: '1:882514435162:ios:a078018b5df4587a618c63',
    messagingSenderId: '882514435162',
    projectId: 'tododemoproject',
    storageBucket: 'tododemoproject.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEv2bnnEIdFt7Gl_PwfL00HYnFdDFTG_E',
    appId: '1:882514435162:ios:13bce0f53ec24aa5618c63',
    messagingSenderId: '882514435162',
    projectId: 'tododemoproject',
    storageBucket: 'tododemoproject.appspot.com',
    iosBundleId: 'com.example.newProject.RunnerTests',
  );
}
